{%set name = "docker-py" %}
{%set version = "1.9.0" %}
{%set hash_type = "sha256" %}
{%set hash_val = "6dc6b914a745786d97817bf35bfc1559834c08517c119f846acdfda9cc7f6d7e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  skip: True  # [win32]
  # win32 requires pypiwin32, which we don't have a build of.
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - requests >=2.5.2
    - six >=1.4.0
    - websocket-client >=0.32.0
    - ssl_match_hostname >=3.5  # [py<35]
    - ipaddress >=1.0.16  # [py<33]

test:
  imports:
    - docker
    - docker.api
    - docker.auth
    - docker.ssladapter
    - docker.unixconn
    - docker.utils
    - docker.utils.ports

about:
  home: https://github.com/docker/docker-py/
  license: Apache 2.0
  summary: 'Python client for Docker.'

extra:
  recipe-maintainers:
    - pmlandwehr
