{% set version = "2.0.2" %}

package:
  name: docker-py
  version: {{ version }}

source:
  fn: docker-py-{{ version }}.tar.gz
  url: https://github.com/docker/docker-py/archive/{{ version }}.tar.gz
  sha256: 1d4a9f65c1e70aec5501c4d84486e3c0d9d0a0dbaa66b48e91f50a108a5c6b9c

build:
  skip: True  # [win32]
  # win32 requires pypiwin32, which we don't have a build of.
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - requests >=2.11.1
    - six >=1.4.0
    - websocket-client >=0.32.0
    - docker-pycreds  >=0.2.1
    - ssl_match_hostname >=3.5  # [py<35]
    - ipaddress >=1.0.16  # [py<33]
    - pypiwin32 >=219  # [win32]

test:
  imports:
    - docker
    - docker.api
    - docker.auth
    - docker.tls
    - docker.transport.unixconn
    - docker.utils
    - docker.utils.ports

about:
  home: https://github.com/docker/docker-py/
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Python client for Docker.'

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - scopatz
