{% set version = "4.0.0" %}

package:
  name: docker-py
  version: {{ version }}

source:
  url: https://github.com/docker/docker-py/archive/{{ version }}.tar.gz
  sha256: 018638ac062759e1a9ab712de27c461d176a73c5fa9680a11b996b8e93e2c358

build:
  skip: True  # [win32]
  # win32 requires pypiwin32, which we don't have a build of.
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - requests >=2.14.2
    - six >=1.10.0
    - websocket-client >=0.32.0
    - docker-pycreds  >=0.3.0
    - ssl_match_hostname >=3.5  # [py<35]
    - ipaddress >=1.0.18  # [py<33]
    - pypiwin32 >=219  # [win32]
    - appdirs >=1.4.3
    - asn1crypto >=0.22.0
    - cffi >=1.10.0
    - cryptography >=1.9
    - docker-pycreds >=0.2.1
    - enum34 >=1.1.6  # [py<34]
    - idna >=2.5
    - packaging >=16.8
    - pycparser >=2.17
    - pyopenssl >=17.0.0
    - pyparsing >=2.2.0
    - websocket-client >=0.40.0

test:
  imports:
    - docker
    - docker.api
    - docker.auth
    - docker.tls
    - docker.utils
    - docker.utils.ports
    - docker.transport.unixconn

about:
  home: https://github.com/docker/docker-py/
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Python client for Docker.'

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
    - scopatz
    - mariusvniekerk
