{% set version = "7.2.0" %}

package:
  name: docker-py
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/docker/docker-{{ version }}.tar.gz
  sha256: cebb93773d334f778e023a7ee352a8d6e13ab1bd3b863a4d4a59dec897df43ac

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.26.0
    - urllib3 >=1.26.0
    - websocket-client >=0.32.0
    - pywin32-on-windows >=304
    - paramiko >=2.4.3

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - docker
    - docker.api
    - docker.auth
    - docker.tls
    - docker.utils
    - docker.utils.ports
    - docker.transport.unixconn
  commands:
    - pip check

about:
  home: https://github.com/docker/docker-py
  summary: A Python library for the Docker Engine API.
  dev_url: https://github.com/docker/docker-py
  doc_url: https://docker-py.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
    - ocefpaf
    - scopatz
    - mariusvniekerk
