{% set version = "5.0.3" %}

package:
  name: docker-py
  version: {{ version }}

source:
  url: https://github.com/docker/docker-py/archive/{{ version }}.tar.gz
  sha256: 0035772df94a86e8db02aac363393755584383aacf50d37b0d55ea817149e1f4
  patches:
    - 0001-loosen-pywin32-pin.patch

build:
  noarch: python
  number: 4
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests >=2.14.2
    - six >=1.10.0
    - websocket-client >=0.32.0
    - docker-pycreds  >=0.3.0
    - appdirs >=1.4.3
    - asn1crypto >=0.22.0
    - cffi >=1.10.0
    - cryptography >=1.9
    - docker-pycreds >=0.2.1
    - idna >=2.5
    - packaging >=16.8
    - pycparser >=2.17
    - pyopenssl >=17.0.0
    - pyparsing >=2.2.0
    - pywin32-on-windows
    - websocket-client >=0.40.0
  run_constrained:
    - pywin32 >=227,<400

test:
  imports:
    - docker
    - docker.api
    - docker.auth
    - docker.tls
    - docker.utils
    - docker.utils.ports
    - docker.transport.unixconn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/docker/docker-py
  summary: A Python library for the Docker Engine API.
  dev_url: https://github.com/docker/docker-py
  doc_url: https://docker-py.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - scopatz
    - mariusvniekerk
